apiVersion: v2
name: monitoring
description: This Helm chart deploys a Prometheus bases monitoring stack
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: kube-prometheus-stack
    version: "91.2.3"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: karma
    version: "2.13.1"
    repository: "https://wiremind.github.io/wiremind-helm-charts"
